name: Links

on:
  push:
    branches: [main]
  pull_request:
  schedule:
    - cron: "41 7 * * 3"

permissions:
  contents: read

jobs:
  lychee:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0
      - uses: lycheeverse/lychee-action@e7477775783ea5526144ba13e8db5eec57747ce8 # v2.9.0
        with:
          args: --no-progress --exclude-path target --exclude-path .venv '**/*.md'
          fail: true
